### ISSUE TITLE
README: pre-built toolchain section has missing link

### ISSUE THREAD

**Issue by WasabiFan** [black-parrot-sdk/black-parrot-sdk#18]
Just saw this new addition -- quite cool!

This issue is just a nit. If I knew what was supposed to be here I'd just open a PR.

The README says:

> Pre-built programs and toolchains can be downloaded at . These are intended for [...]

I assume there's supposed to be a link or archive name before the period.

**Comment by dpetrisko** [comment]
Thanks! Updated
