### ISSUE TITLE
Support Linux kernel 5.15 and newer opensbi version

### ISSUE THREAD

**Issue by Yuan-Mao** [black-parrot-sdk/black-parrot-sdk#30]
In order to use the Litex Ethernet driver on kernel 5.15+, I am now actively working on bringing up kernel 5.15 on BP.

Also, with kernel 5.15, we might want to use newer version of opensbi because I have seen the kernel emit rdtime instruction in U-mode and the [current opensbi version](https://github.com/black-parrot-sdk/opensbi/commit/eac24d8778eb8497629431af523d05fd54b42d42) in our SDK doesn't seem to emulate that instruction properly. I'm now also looking at this as well, and I will file a PR for each of them in the future.

**Comment by dpetrisko** [comment]
Cool!

**Comment by Yuan-Mao** [comment]
I was able to run Linux kernel 5.15 + opensbi v1.0 on dromajo with multicore support (at least I haven't encountered any kernel panic).

Before creating PR, I think first we need to sync the master branch from our forked opensbi repo with the official repo. After that, should I base my work on branch 'blackparrot_mods' or should I create a brand-new branch starting right from the latest master branch after the sync? I think creating a new one would be easier for me because most of the changes in 'blackparrot_mods' are outdated, but by doing so we will end up creating a branch whenever we bump opensbi.

**Comment by dpetrisko** [comment]
Cool! Make a new branch

**Comment by muwyse** [comment]
Is this ready for a PR and update to the SDK master branch? I see the following PRs both merged already in the respective repos:
- https://github.com/black-parrot-sdk/bp-linux/pull/6
- https://github.com/black-parrot-sdk/opensbi/pull/2

Are there any other changes required (i.e., Dromajo, RTL, etc.)?

**Comment by dpetrisko** [comment]
Think it should be good to go, just need FPGA validation

**Comment by muwyse** [comment]
@Yuan-Mao Single core linux looks good. I was able to boot on FPGA, including with 2 GiB of DRAM allocated and showing available to the OS in /proc/meminfo.

Multicore linux (2 or more cores) is failing in Dromajo simulation when the boot reaches secondary CPU bringup. Dromajo reports an invalid physical address of 0x1300000.

I believe there is also a bug related to the param rom implementation in Dromajo, which needs a small update for the latest aviary param rom changes.

**Comment by muwyse** [comment]
This issue appears to be present on current SDK master, too. I'm guessing it is an unimplemented BP thing, perhaps?

**Comment by dpetrisko** [comment]
Invalid physical address sounds more like a device trying to get initialized that doesn’t exist? But would have to see the trace to make sure

**Comment by muwyse** [comment]
Update: false alarm on multicore linux on dromajo. Turns out the --ncpus flag to dromajo is important... I've successfully emulated 2, 4, and 8 core Linux boots. Still need to verify multicore linux on multicore FPGA build.

**Comment by muwyse** [comment]
Closed with #41
