### ISSUE TITLE
[Questions] Detect MPRV bit in opensbi trap redirect

### ISSUE THREAD

**Issue by Yuan-Mao** [black-parrot-sdk/black-parrot-sdk#31]
Hi,
I have a question about this line in sbi_trap_redirect:
https://github.com/black-parrot-sdk/opensbi/blob/blackparrot_mods/lib/sbi/sbi_trap.c#L95

Just wondering in what situation we would get MPRV set to 1 during sbi_trap_redirect()? From the dromajo simulation running Linux kernel, it seems to me this 'in_emulation' variable will never be set.

Thanks!

**Comment by Yuan-Mao** [comment]
Note: the line is from this commit: https://github.com/black-parrot-sdk/opensbi/commit/6dd8562d8ef7825b813eca554f6094a3c36eff8e#diff-dd24cab4466c9495164a9d025642bd2f2e592dbfbaf7f313f57544bca26273bb

**Comment by farzamgl** [comment]
When/if we get a trap when running emulation code MPRV will be set. For example if we get a page-fault when emulating AMO instructions we need to redirect it to kernel mode to be processed.
