### ISSUE TITLE
Opensbi: Put FDT back in text section

### ISSUE THREAD

**Issue by Yuan-Mao** [black-parrot-sdk/black-parrot-sdk#35]
https://github.com/black-parrot-sdk/opensbi/blob/5921c74852dcd96f5b0acbf74d8401662151fd80/firmware/fw_payload.elf.ldS#L18

Hi, I'm not sure if we still need this separate fdt section in the linker script in opensbi? I just happened to run into an issue where gcc will occasionally fail to put that fdt section into an ELF segment, which will make the entire fdt data missing in the NBF file.

One way of enforcing it is to use PHDRS in the link script, but adding one PHDRS means users have to start taking care of the arrangement of all the other segments, so there seems to be no easy way to just add an additional ELF segment for the fdt section. Therefore I wonder if we still need this fdt section.

Thanks!

**Comment by dpetrisko** [comment]
I believe fixed with https://github.com/black-parrot-sdk/opensbi/pull/3
