### ISSUE TITLE
SDK Build Error

### ISSUE THREAD

**Issue by amithmath** [black-parrot-sdk/black-parrot-sdk#52]
Hello,

While I was trying build black-parrot-sdk, I am getting error: <path_to_black-parrot>/zynq-parrot/software/import/black-parrot-sdk/install/bin/../libexec/gcc/riscv64-unknown-elf-dramfs/9.2.0/cc1: error while loading shared libraries: libmpfr.so.6: cannot open shared object file: No such file or directory  Can you please help with this issue? I am using pre built image from: https://github.com/black-parrot-sdk/black-parrot-sdk/releases (tools.tar.gz)  and I am using CentOS 7

Many Thanks!

**Comment by dpetrisko** [comment]
Make sure to have libmpfr-dev installed

**Comment by amithmath** [comment]
OK thanks
