### ISSUE TITLE
Update riscv-gnu-toolchain for more efficient submodule checkout

### ISSUE THREAD

**Issue by muwyse** [black-parrot-sdk/black-parrot-sdk#9]
The current upstream riscv-gnu-toolchain repo has been updated to remove the need for --recursive option when cloning the repo.  The build system fetches code as required. See here: https://github.com/riscv/riscv-gnu-toolchain

I assume would also apply to having the toolchain as a submodule, so perhaps our fork should try to incorporate these updates from upstream.

**Comment by dpetrisko** [comment]
riscv-gnu-toolchain is updated to 12
